### ISSUE TITLE
Simplified mutes

### ISSUE THREAD

**Issue by vsomayaji** [aira/flutter_aira#34]
There are a few things about our mutes implementation that don't sit well with me:

1. There's a different way to mute a track _before_ joining a `Room`:
   ```dart
   _localMediaStream.getAudioTracks()[0].enabled = false;
   ```
   And _after_ joining a `Room`:
   ```dart
   _room.setAudioMuted(true);
   ```
   If you use the first way _after_ joining a `Room`, the mute states of the track and the `Room` will be out of sync.

2. The `Room` does not expose getters for its mute states. If the mute states of the track and the `Room` get out of sync, there's no way to know.

3. `Room.setAudioMuted` and `Room.setVideoMuted` perform an async call (to `_updateParticipantStatus`) but do not return a `Future`.

4. `Room.setVideoMuted` only mutes the _active_ video track. Replacing the video track (with `Room.replaceStream`) will not preserve the mute state.

5. `Room.setVideoMuted` affects the presentation even though the presentation was intended to be thought of as a separate video track.

Now that we've discovered that we can "mute" a track by providing the corresponding transceiver a `null` track, I think we can switch to an implementation where the mute states are always managed by the `Room`. The interface could look like this:

```dart
  /// Whether the local audio is muted.
  bool get isAudioMuted;

  /// Mutes or un-mutes the local audio.
  Future<void> setAudioMuted(bool muted);

  /// Whether the local video is muted.
  bool get isVideoMuted;

  /// Mutes or un-mutes the local video.
  Future<void> setVideoMuted(bool muted);

  /// Whether the presentation is muted.
  bool get isPresentationMuted;

  /// Mutes or un-mutes the presentation.
  Future<void> setPresentationMuted(bool muted);

  /// Enables or disables privacy mode.
  ///
  /// In privacy mode, the local audio, video and presentation are _all_ muted. This is equivalent to calling
  /// [setAudioMuted], [setVideoMuted] and [setPresentationMuted], and is intended as a convenience for apps that do not
  /// support muting the tracks independently.
  Future<void> setPrivacyMode(bool enabled);
```

I believe this would address all of the issues above. For example, if the video is muted in the `Room` and the video track is replaced, the video will stay muted.

What do you think? Good idea or a bad one?

**Comment by ipainchaud** [comment]
1. good point!
2. I believe you meant to say: "if the Explorer-UI's mute status and Room's status get out of sync" because Room's mute status used to depend on the tracks, so the room and the tracks could never get out of sync.
3. Good catch! that was a bug!
4. That was as designed! If someone mutes his video and then start a presentation, we don't want to start the presentation in a muted status. Plus, when you stop the presentation (not muted) and you had your video muted, you'd hope that your muted webcam would remain muted.
5. I understand your point and it will be clearer for the users to have a different methods for the different streams. This will also have the side effect that not all applications using the SDK will have the same behavior with the muting of the different streams... this could be seen as a plus or a cons.
